version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go
    ports:
      - "3006:3306"
    volumes:
      - /Users/rafaeldurelli/Documents/development/golang/radapp
